/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import utilities.LoadRecord;

/**
 *
 * @author vigneshguna
 */
public class CreateJPanel extends javax.swing.JPanel {
    PatientDirectory patientDirectory;
    ButtonGroup commGroup;
    boolean isLoadAllDone = false;

    CreateJPanel(PatientDirectory patientDirectory) {
        initComponents();
        commGroup = new ButtonGroup();
        asianRadio.setActionCommand("Asian");
        americanRadio.setActionCommand("American");
        latinoRadio.setActionCommand("Latino");
        canadianRadio.setActionCommand("Canadian");
        africanRadio.setActionCommand("African");
        
        commGroup.add(asianRadio);
        commGroup.add(americanRadio);
        commGroup.add(latinoRadio);
        commGroup.add(canadianRadio);
        commGroup.add(africanRadio);
        
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        streetTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        asianRadio = new javax.swing.JRadioButton();
        americanRadio = new javax.swing.JRadioButton();
        latinoRadio = new javax.swing.JRadioButton();
        canadianRadio = new javax.swing.JRadioButton();
        africanRadio = new javax.swing.JRadioButton();
        btnLoad = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("Name :");

        jLabel3.setText("Age :");

        jLabel4.setText("Home Street :");

        jLabel5.setText("City :");

        jLabel6.setText("Community :");

        jLabel7.setText("Contact Number :");

        btnAdd.setText("Add Patient");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        asianRadio.setText("Asian");
        asianRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asianRadioActionPerformed(evt);
            }
        });

        americanRadio.setText("American");

        latinoRadio.setText("Latino");

        canadianRadio.setText("Canadian");

        africanRadio.setText("African");

        btnLoad.setText("Load Patient & Vital records");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 153, 0));
        lblTitle.setText("Create Patient");

        jLabel8.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("ABC Hospitals");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asianRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(americanRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(latinoRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(canadianRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(africanRadio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(asianRadio)
                    .addComponent(americanRadio)
                    .addComponent(latinoRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canadianRadio)
                    .addComponent(africanRadio))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Person person = new Person();
        
        //validation ?
        
        person.setName(nameTextField.getText());
        person.setAge(Integer.parseInt(ageTextField.getText()));
        person.setHomeAddress(streetTextField.getText());
        person.setCity(cityTextField.getText());
        person.setContactDirectory(Long.parseLong(contactTextField.getText()));
        person.setCommunity(commGroup.getSelection().getActionCommand());
        
        Patient patient = patientDirectory.addNewPatient();
        
        patient.setPerson(person);
        
        //duplicacy ?
        
        clearFields();
        JOptionPane.showMessageDialog(this, "Patient Record is added !");
    }//GEN-LAST:event_btnAddActionPerformed

    private void asianRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asianRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asianRadioActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        LoadRecord lr = new LoadRecord(patientDirectory);
        if (!isLoadAllDone) {
            lr.loadAll();
            isLoadAllDone = true;
            JOptionPane.showMessageDialog(this, "The available Patient Records are loaded !");
        } else {
            JOptionPane.showMessageDialog(this, "They are already loadded");
        }
    }//GEN-LAST:event_btnLoadActionPerformed
    private void clearFields() {
        nameTextField.setText("");
        ageTextField.setText("");
        streetTextField.setText("");
        cityTextField.setText("");
        contactTextField.setText("");
        commGroup.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton africanRadio;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JRadioButton americanRadio;
    private javax.swing.JRadioButton asianRadio;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton canadianRadio;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton latinoRadio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField streetTextField;
    // End of variables declaration//GEN-END:variables
}
